### Get all contacts
GET http://localhost:3000/contact

### Swagger API docs
swagger API http://localhost:3000/api-docs

### Get a single contact by ID
GET http://localhost:3000/contact/68263e7c931fccbb47c15e1f

### Create a new contact
POST http://localhost:3000/contact
Content-Type: application/json

{
  "firstName": "Mawuli",
  "lastName": "Ayikpa",
  "email": "mawuli@gmail.com",
  "favoriteColor": "White",
  "birthday": "1992-01-01"
}

### Update a contact
PUT http://localhost:3000/contact/682cd22bb1260d6c9cf18ccb

{
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@gmail.com.com",
  "favoriteColor": "Teal",
  "birthday": "1992-08-15"
}

### Delete a contact
DELETE http://localhost:3000/contact/682cd22bb1260d6c9cf18ccb
